### ISSUE TITLE
tenderly export not working

### ISSUE THREAD

**Issue by lodelux** [Tenderly/tenderly-cli#94] opened 2022-07-15 13:13 UTC
I'm creating a node using hardhat. when I try to export a local transaction It loops through this message over the node logs

`eth_getStorageAt`
  `Errors encountered in param 1: Storage slot argument must have a length of 66 ("0x" + 32 bytes), but '0x0' has a length of 3`

this is my package.json

`{
  "dependencies": {
    "@tenderly/hardhat-tenderly": "^1.1.4",
    "hardhat": "^2.10.1",
    "yarn-upgrade-all": "^0.7.1"
  },
  "devDependencies": {
    "@ethersproject/abi": "^5.6.4",
    "@ethersproject/providers": "^5.6.8",
    "@nomicfoundation/hardhat-chai-matchers": "^1.0.2",
    "@nomicfoundation/hardhat-network-helpers": "^1.0.3",
    "@nomicfoundation/hardhat-toolbox": "^1.0.2",
    "@nomiclabs/hardhat-ethers": "^2.1.0",
    "@nomiclabs/hardhat-etherscan": "^3.1.0",
    "@typechain/ethers-v5": "^10.1.0",
    "@typechain/hardhat": "^6.1.2",
    "chai": "^4.3.6",
    "ethers": "^5.6.9",
    "hardhat-gas-reporter": "^1.0.8",
    "solidity-coverage": "^0.7.21",
    "typechain": "^8.1.0"
  }
}
`

**Comment by delta003** [comment] 2022-07-18 12:35
We'll look into this but can not provide ETA at this point. Are there any steps to reproduce that you can share?

In the meantime, have you tried using Tenderly Forks for this workflow? You can use fork just as local node (it implements JSON-RPC) and every transaction will be visible on fork with Tenderly Debugger

**Comment by delta003** [comment] 2022-07-18 14:17
Same as https://github.com/Tenderly/tenderly-cli/issues/95, so closing this one since there is more details in the other issue

**Closed by delta003** 2022-07-18 14:17 UTC
